project:
  type: book

execute:
  freeze: auto

book:
  title: "Ciência de Dados Aplicada ao Direito"
  author: "Julio Trecenti (Insper)"
  date: "23/07/2025"
  chapters:
    - index.qmd
    - 00-introducao.qmd
    - part: "Planejando pesquisa e construindo dados"
      chapters:
        - 01-operacionalizacao-conceitos.qmd
        - 02-fontes-dados-judiciario.qmd
        - 03-raspagem-dados.qmd
        - 04-tecnicas-amostragem.qmd
        - 05-tipos-dados.qmd
        - 06-construcao-limpeza-dados.qmd
    - part: "Análise estatística"
      chapters:
        - 07-medidas-posicao-variabilidade.qmd
        - 08-visualizacao-dados-juridicos.qmd
        - 09-correlacao-causalidade.qmd
        - 10-probabilidade-distribuicoes.qmd
        - 11-intervalo-confianca.qmd
        - 12-testes-hipoteses.qmd
    - part: "Técnicas estatísticas e aplicações"
      chapters:
        - 13-analise-regressao.qmd
        - 14-modelos-classificacao.qmd
        - 15-modelagem-tempos-processos.qmd
        - 16-aplicacoes-corporativas.qmd
    - resumo.qmd
    - refs.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

filters:
  - pyodide
