[project]
name = "cdad-book"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "juscraper>=0.1.3",
    "openai>=1.102.0",
    "pandas>=2.3.2",
]
